### ISSUE TITLE
Feature : compute md5 and expires query parameters

### ISSUE THREAD

**Issue by r0mdau** [Trois-Six/plugin-securelink#1]
Hi @Trois-Six , 

Do you plan to add a second capability to this plugin by enabling the use of secure links with md5 and expires query parameters ?

Glad to help if needed.

**Comment by trois-six** [comment]
Hi,
Yes! That's in my list.
Pierre

**Comment by trois-six** [comment]
Done with https://github.com/Trois-Six/plugin-securelink/commit/2473c42ede6fe4bfb66197480303d9c7e236e8c8.
